/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Exam {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "lessonId", skip_serializing_if = "Option::is_none")]
    pub lesson_id: Option<i32>,
    #[serde(rename = "lesson", skip_serializing_if = "Option::is_none")]
    pub lesson: Option<Box<models::Lesson>>,
    #[serde(rename = "teacherId", skip_serializing_if = "Option::is_none")]
    pub teacher_id: Option<i32>,
    #[serde(rename = "teacher", skip_serializing_if = "Option::is_none")]
    pub teacher: Option<Box<models::Teacher>>,
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<i32>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<models::Group>>,
    #[serde(rename = "cabinet", skip_serializing_if = "Option::is_none")]
    pub cabinet: Option<i32>,
    #[serde(rename = "examStart", skip_serializing_if = "Option::is_none")]
    pub exam_start: Option<String>,
}

impl Exam {
    pub fn new() -> Exam {
        Exam {
            id: None,
            lesson_id: None,
            lesson: None,
            teacher_id: None,
            teacher: None,
            group_id: None,
            group: None,
            cabinet: None,
            exam_start: None,
        }
    }
}

