/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetScheduleAdmin {
    #[serde(rename = "dayOfWeek", skip_serializing_if = "Option::is_none")]
    pub day_of_week: Option<models::DayOfWeek>,
    #[serde(rename = "schedules", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub schedules: Option<Option<Vec<models::LessonSchedule>>>,
}

impl GetScheduleAdmin {
    pub fn new() -> GetScheduleAdmin {
        GetScheduleAdmin {
            day_of_week: None,
            schedules: None,
        }
    }
}

