/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ktp {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "lessonId", skip_serializing_if = "Option::is_none")]
    pub lesson_id: Option<i32>,
    #[serde(rename = "lesson", skip_serializing_if = "Option::is_none")]
    pub lesson: Option<Box<models::Lesson>>,
    #[serde(rename = "course", skip_serializing_if = "Option::is_none")]
    pub course: Option<i32>,
    #[serde(rename = "educationType", skip_serializing_if = "Option::is_none")]
    pub education_type: Option<models::EducationTypes>,
    #[serde(rename = "lessonHours", skip_serializing_if = "Option::is_none")]
    pub lesson_hours: Option<i32>,
}

impl Ktp {
    pub fn new() -> Ktp {
        Ktp {
            id: None,
            lesson_id: None,
            lesson: None,
            course: None,
            education_type: None,
            lesson_hours: None,
        }
    }
}

