/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LessonScheduleWithWork {
    #[serde(rename = "lessonSchedule", skip_serializing_if = "Option::is_none")]
    pub lesson_schedule: Option<Box<models::LessonSchedule>>,
    #[serde(rename = "work", skip_serializing_if = "Option::is_none")]
    pub work: Option<Box<models::Work>>,
    #[serde(rename = "scheduleMove", skip_serializing_if = "Option::is_none")]
    pub schedule_move: Option<Box<models::ScheduleMove>>,
    #[serde(rename = "scheduleAdd", skip_serializing_if = "Option::is_none")]
    pub schedule_add: Option<Box<models::ScheduleAdd>>,
}

impl LessonScheduleWithWork {
    pub fn new() -> LessonScheduleWithWork {
        LessonScheduleWithWork {
            lesson_schedule: None,
            work: None,
            schedule_move: None,
            schedule_add: None,
        }
    }
}

