/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LessonSchedule {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "lessonId", skip_serializing_if = "Option::is_none")]
    pub lesson_id: Option<i32>,
    #[serde(rename = "lesson", skip_serializing_if = "Option::is_none")]
    pub lesson: Option<Box<models::Lesson>>,
    #[serde(rename = "cabinet", skip_serializing_if = "Option::is_none")]
    pub cabinet: Option<i32>,
    #[serde(rename = "week", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub week: Option<Option<String>>,
    #[serde(rename = "teacherId", skip_serializing_if = "Option::is_none")]
    pub teacher_id: Option<i32>,
    #[serde(rename = "teacher", skip_serializing_if = "Option::is_none")]
    pub teacher: Option<Box<models::Teacher>>,
    #[serde(rename = "dayOfWeek", skip_serializing_if = "Option::is_none")]
    pub day_of_week: Option<models::DayOfWeek>,
    #[serde(rename = "subNumber", skip_serializing_if = "Option::is_none")]
    pub sub_number: Option<i32>,
    #[serde(rename = "lessonNumber", skip_serializing_if = "Option::is_none")]
    pub lesson_number: Option<i32>,
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<i32>,
    #[serde(rename = "subGroup", skip_serializing_if = "Option::is_none")]
    pub sub_group: Option<i32>,
}

impl LessonSchedule {
    pub fn new() -> LessonSchedule {
        LessonSchedule {
            id: None,
            lesson_id: None,
            lesson: None,
            cabinet: None,
            week: None,
            teacher_id: None,
            teacher: None,
            day_of_week: None,
            sub_number: None,
            lesson_number: None,
            group_id: None,
            sub_group: None,
        }
    }
}

