/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateKtpDto {
    #[serde(rename = "ktpId", skip_serializing_if = "Option::is_none")]
    pub ktp_id: Option<i32>,
    #[serde(rename = "lessonHours", skip_serializing_if = "Option::is_none")]
    pub lesson_hours: Option<i32>,
}

impl UpdateKtpDto {
    pub fn new() -> UpdateKtpDto {
        UpdateKtpDto {
            ktp_id: None,
            lesson_hours: None,
        }
    }
}

