/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateLessonDto {
    #[serde(rename = "lessonId", skip_serializing_if = "Option::is_none")]
    pub lesson_id: Option<i32>,
    #[serde(rename = "lessonName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lesson_name: Option<Option<String>>,
    #[serde(rename = "subLessonName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sub_lesson_name: Option<Option<String>>,
}

impl UpdateLessonDto {
    pub fn new() -> UpdateLessonDto {
        UpdateLessonDto {
            lesson_id: None,
            lesson_name: None,
            sub_lesson_name: None,
        }
    }
}

