/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTeacherDto {
    #[serde(rename = "teacherId", skip_serializing_if = "Option::is_none")]
    pub teacher_id: Option<i32>,
    #[serde(rename = "teacherFio", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub teacher_fio: Option<Option<String>>,
    #[serde(rename = "initials", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub initials: Option<Option<String>>,
}

impl UpdateTeacherDto {
    pub fn new() -> UpdateTeacherDto {
        UpdateTeacherDto {
            teacher_id: None,
            teacher_fio: None,
            initials: None,
        }
    }
}

