/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EducationTypes {
    #[serde(rename = "Sso")]
    Sso,
    #[serde(rename = "Vo")]
    Vo,

}

impl std::fmt::Display for EducationTypes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sso => write!(f, "Sso"),
            Self::Vo => write!(f, "Vo"),
        }
    }
}

impl Default for EducationTypes {
    fn default() -> EducationTypes {
        Self::Sso
    }
}

