/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWorksScheduleDto {
    #[serde(rename = "workType", skip_serializing_if = "Option::is_none")]
    pub work_type: Option<models::WorkTypeEnum>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

impl GetWorksScheduleDto {
    pub fn new() -> GetWorksScheduleDto {
        GetWorksScheduleDto {
            work_type: None,
            date: None,
        }
    }
}

