/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetScheduleForOneGroup {
    #[serde(rename = "date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date: Option<Option<String>>,
    #[serde(rename = "schedules", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub schedules: Option<Option<Vec<models::LessonScheduleWithWork>>>,
    #[serde(rename = "practice", skip_serializing_if = "Option::is_none")]
    pub practice: Option<Box<models::Practice>>,
    #[serde(rename = "exam", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exam: Option<Option<Vec<models::Exam>>>,
}

impl GetScheduleForOneGroup {
    pub fn new() -> GetScheduleForOneGroup {
        GetScheduleForOneGroup {
            date: None,
            schedules: None,
            practice: None,
            exam: None,
        }
    }
}

