/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSkippedLessonsDto {
    #[serde(rename = "lessonSchedule", skip_serializing_if = "Option::is_none")]
    pub lesson_schedule: Option<Box<models::LessonSchedule>>,
    #[serde(rename = "work", skip_serializing_if = "Option::is_none")]
    pub work: Option<Box<models::Work>>,
    #[serde(rename = "practice", skip_serializing_if = "Option::is_none")]
    pub practice: Option<Box<models::Practice>>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

impl GetSkippedLessonsDto {
    pub fn new() -> GetSkippedLessonsDto {
        GetSkippedLessonsDto {
            lesson_schedule: None,
            work: None,
            practice: None,
            date: None,
        }
    }
}

