/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWorksGroupDto {
    #[serde(rename = "workType", skip_serializing_if = "Option::is_none")]
    pub work_type: Option<models::WorkTypeEnum>,
    #[serde(rename = "lessonNumbers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lesson_numbers: Option<Option<Vec<i32>>>,
}

impl GetWorksGroupDto {
    pub fn new() -> GetWorksGroupDto {
        GetWorksGroupDto {
            work_type: None,
            lesson_numbers: None,
        }
    }
}

