/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleMove {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "fromLessonScheduleId", skip_serializing_if = "Option::is_none")]
    pub from_lesson_schedule_id: Option<i32>,
    #[serde(rename = "fromLessonSchedule", skip_serializing_if = "Option::is_none")]
    pub from_lesson_schedule: Option<Box<models::LessonSchedule>>,
    #[serde(rename = "fromDate", skip_serializing_if = "Option::is_none")]
    pub from_date: Option<String>,
    #[serde(rename = "toDate", skip_serializing_if = "Option::is_none")]
    pub to_date: Option<String>,
    #[serde(rename = "toLessonNumber", skip_serializing_if = "Option::is_none")]
    pub to_lesson_number: Option<i32>,
    #[serde(rename = "toSubLessonNumber", skip_serializing_if = "Option::is_none")]
    pub to_sub_lesson_number: Option<i32>,
}

impl ScheduleMove {
    pub fn new() -> ScheduleMove {
        ScheduleMove {
            id: None,
            from_lesson_schedule_id: None,
            from_lesson_schedule: None,
            from_date: None,
            to_date: None,
            to_lesson_number: None,
            to_sub_lesson_number: None,
        }
    }
}

