/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleMoveDto {
    #[serde(rename = "fromLessonScheduleId", skip_serializing_if = "Option::is_none")]
    pub from_lesson_schedule_id: Option<i32>,
    #[serde(rename = "fromDate", skip_serializing_if = "Option::is_none")]
    pub from_date: Option<String>,
    #[serde(rename = "toDate", skip_serializing_if = "Option::is_none")]
    pub to_date: Option<String>,
    #[serde(rename = "toLessonNumber", skip_serializing_if = "Option::is_none")]
    pub to_lesson_number: Option<i32>,
    #[serde(rename = "toSubLessonNumber", skip_serializing_if = "Option::is_none")]
    pub to_sub_lesson_number: Option<i32>,
}

impl ScheduleMoveDto {
    pub fn new() -> ScheduleMoveDto {
        ScheduleMoveDto {
            from_lesson_schedule_id: None,
            from_date: None,
            to_date: None,
            to_lesson_number: None,
            to_sub_lesson_number: None,
        }
    }
}

