/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleAddDto {
    #[serde(rename = "toDate", skip_serializing_if = "Option::is_none")]
    pub to_date: Option<String>,
    #[serde(rename = "toLessonNumber", skip_serializing_if = "Option::is_none")]
    pub to_lesson_number: Option<i32>,
    #[serde(rename = "toSubLessonNumber", skip_serializing_if = "Option::is_none")]
    pub to_sub_lesson_number: Option<i32>,
    #[serde(rename = "toSubGroup", skip_serializing_if = "Option::is_none")]
    pub to_sub_group: Option<i32>,
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<i32>,
    #[serde(rename = "lessonId", skip_serializing_if = "Option::is_none")]
    pub lesson_id: Option<i32>,
    #[serde(rename = "teacherId", skip_serializing_if = "Option::is_none")]
    pub teacher_id: Option<i32>,
    #[serde(rename = "cabinet", skip_serializing_if = "Option::is_none")]
    pub cabinet: Option<i32>,
}

impl ScheduleAddDto {
    pub fn new() -> ScheduleAddDto {
        ScheduleAddDto {
            to_date: None,
            to_lesson_number: None,
            to_sub_lesson_number: None,
            to_sub_group: None,
            group_id: None,
            lesson_id: None,
            teacher_id: None,
            cabinet: None,
        }
    }
}

