/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Teacher {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "fio", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fio: Option<Option<String>>,
    #[serde(rename = "initials", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub initials: Option<Option<String>>,
}

impl Teacher {
    pub fn new() -> Teacher {
        Teacher {
            id: None,
            fio: None,
            initials: None,
        }
    }
}

