/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Work {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "workType", skip_serializing_if = "Option::is_none")]
    pub work_type: Option<models::WorkTypeEnum>,
    #[serde(rename = "groupKtpId", skip_serializing_if = "Option::is_none")]
    pub group_ktp_id: Option<i32>,
    #[serde(rename = "lessonScheduleId", skip_serializing_if = "Option::is_none")]
    pub lesson_schedule_id: Option<i32>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "lessonNumber", skip_serializing_if = "Option::is_none")]
    pub lesson_number: Option<i32>,
}

impl Work {
    pub fn new() -> Work {
        Work {
            id: None,
            work_type: None,
            group_ktp_id: None,
            lesson_schedule_id: None,
            date: None,
            lesson_number: None,
        }
    }
}

