/*
 * BsacScheduleApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkTypeEnum {
    #[serde(rename = "Laboratory")]
    Laboratory,
    #[serde(rename = "Practical")]
    Practical,
    #[serde(rename = "Okr")]
    Okr,
    #[serde(rename = "DifferentiatedTest")]
    DifferentiatedTest,

}

impl std::fmt::Display for WorkTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Laboratory => write!(f, "Laboratory"),
            Self::Practical => write!(f, "Practical"),
            Self::Okr => write!(f, "Okr"),
            Self::DifferentiatedTest => write!(f, "DifferentiatedTest"),
        }
    }
}

impl Default for WorkTypeEnum {
    fn default() -> WorkTypeEnum {
        Self::Laboratory
    }
}

