name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
          name: bsac-cli
          path: target/release/bsac-cli
